/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biometria.main;

import com.biometria.main.BaseDeDadosBiometrico;

/**
 *
 * @author Bortolo
 */
public class DadosFrame extends javax.swing.JFrame {

    /**
     * Creates new form DadosFrame
     */
    public DadosFrame() {
        initComponents();
        txtNome.setText(BaseDeDadosBiometrico.nome);
        txtSobrenome.setText(BaseDeDadosBiometrico.sobrenome);
        
        if(BaseDeDadosBiometrico.nivel == 1){
           jComboBox.setSelectedIndex(0);
        }
        if(BaseDeDadosBiometrico.nivel == 2){
           rbNivelDois.setEnabled(true);
           jComboBox.setSelectedIndex(1);
        }
        if(BaseDeDadosBiometrico.nivel == 3){
           rbNivelDois.setEnabled(true);
           RBNivelTres.setEnabled(true);
           jComboBox.setSelectedIndex(2);
        }
        
        jTextArea1.setText("<><><> NÍVEL 1 <><><>" + "\n" + "Informações estratégicas sobre as propriedades ruruais" + "\n" + 
                    "que utilizam agrotóxicos proibidos por causarem grandes impactos" + "\n" + 
                    "nos lenções freáticos, rios e mares.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bgNivelAcesso = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbNivelUm = new javax.swing.JRadioButton();
        rbNivelDois = new javax.swing.JRadioButton();
        RBNivelTres = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jComboBox = new javax.swing.JComboBox<>();
        txtSobrenome = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dados Abertos");
        setResizable(false);

        jLabel2.setText("Nome:");

        jLabel3.setText("Sobrenome:");

        jLabel4.setText("Acesso:");

        bgNivelAcesso.add(rbNivelUm);
        rbNivelUm.setSelected(true);
        rbNivelUm.setText("Nível 1");
        rbNivelUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNivelUmActionPerformed(evt);
            }
        });

        bgNivelAcesso.add(rbNivelDois);
        rbNivelDois.setText("Nível 2");
        rbNivelDois.setEnabled(false);
        rbNivelDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNivelDoisActionPerformed(evt);
            }
        });

        bgNivelAcesso.add(RBNivelTres);
        RBNivelTres.setText("Nível 3");
        RBNivelTres.setEnabled(false);
        RBNivelTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBNivelTresActionPerformed(evt);
            }
        });

        jLabel5.setText("Nível de Acesso:");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/biometria/resources/DADOS FUNDAMENTAIS SOBRE O MINISTÉRIO DO MEIO AMBIENTE.png"))); // NOI18N

        txtNome.setEditable(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Público", "Diretor de Divisão", "Ministro do Meio Ambiente", "" }));
        jComboBox.setEnabled(false);
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        txtSobrenome.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbNivelUm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbNivelDois)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RBNivelTres))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSobrenome)
                                .addComponent(jComboBox, 0, 171, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbNivelUm)
                    .addComponent(rbNivelDois)
                    .addComponent(RBNivelTres))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(461, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RBNivelTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBNivelTresActionPerformed
        if(RBNivelTres.isSelected()){
            jTextArea1.setText("");
            jTextArea1.setText("<><><> NÍVEL 3 <><><>" + "\n" + "Informações estratégicas sobre as propriedades ruruais" + "\n" + 
                    "que utilizam agrotóxicos proibidos por causarem grandes impactos" + "\n" + 
                    "nos lenções freáticos, rios e mares.");
        }
    }//GEN-LAST:event_RBNivelTresActionPerformed

    private void rbNivelUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNivelUmActionPerformed

        if(rbNivelUm.isSelected()){
            jTextArea1.setText("");
            jTextArea1.setText("<><><> NÍVEL 1 <><><>" + "\n" + "Informações estratégicas sobre as propriedades ruruais" + "\n" + 
                    "que utilizam agrotóxicos proibidos por causarem grandes impactos" + "\n" + 
                    "nos lenções freáticos, rios e mares.");
        }
    }//GEN-LAST:event_rbNivelUmActionPerformed

    private void rbNivelDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNivelDoisActionPerformed
        if(rbNivelDois.isSelected()){
            jTextArea1.setText("");
            jTextArea1.setText("<><><> NÍVEL 2 <><><>" + "\n" + "Informações estratégicas sobre as propriedades ruruais" + "\n" + 
                    "que utilizam agrotóxicos proibidos por causarem grandes impactos" + "\n" + 
                    "nos lenções freáticos, rios e mares.");
        }
    }//GEN-LAST:event_rbNivelDoisActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBNivelTres;
    private javax.swing.ButtonGroup bgNivelAcesso;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rbNivelDois;
    private javax.swing.JRadioButton rbNivelUm;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
